# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagement.Class'),
        ),
        migrations.AlterField(
            model_name='period',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagement.Subject'),
        ),
    ]
