# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 08:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0002_auto_20160729_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='schedule',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='StudentManagement.FacultyTimeTable'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
