# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0003_auto_20160729_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentManagement.FacultyTimeTable'),
        ),
        migrations.AlterField(
            model_name='facultytimetable',
            name='period2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period2', to='StudentManagement.Period'),
        ),
        migrations.AlterField(
            model_name='facultytimetable',
            name='period3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period3', to='StudentManagement.Period'),
        ),
        migrations.AlterField(
            model_name='facultytimetable',
            name='period4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period4', to='StudentManagement.Period'),
        ),
        migrations.AlterField(
            model_name='facultytimetable',
            name='period5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period5', to='StudentManagement.Period'),
        ),
    ]
