# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0006_auto_20160730_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultytimetable',
            name='period2',
            field=models.ManyToManyField(blank=True, related_name='period2', to='StudentManagement.Period'),
        ),
        migrations.AlterField(
            model_name='facultytimetable',
            name='period3',
            field=models.ManyToManyField(blank=True, related_name='period3', to='StudentManagement.Period'),
        ),
        migrations.AlterField(
            model_name='facultytimetable',
            name='period4',
            field=models.ManyToManyField(blank=True, related_name='period4', to='StudentManagement.Period'),
        ),
        migrations.AlterField(
            model_name='facultytimetable',
            name='period5',
            field=models.ManyToManyField(blank=True, related_name='period5', to='StudentManagement.Period'),
        ),
    ]
