# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0007_auto_20160730_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendencetable',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='studentattendencetable',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='studentattendencetable',
            name='subject3',
        ),
        migrations.RemoveField(
            model_name='studentattendencetable',
            name='subject4',
        ),
        migrations.RemoveField(
            model_name='studentattendencetable',
            name='subject5',
        ),
        migrations.RemoveField(
            model_name='studentattendencetable',
            name='subject6',
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendence',
        ),
        migrations.AddField(
            model_name='subjectattendencetable',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentManagement.Student'),
        ),
        migrations.DeleteModel(
            name='StudentAttendenceTable',
        ),
    ]
