# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0008_auto_20160730_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultytimetable',
            name='period1',
        ),
        migrations.AddField(
            model_name='facultytimetable',
            name='period1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period1', to='StudentManagement.Period'),
        ),
        migrations.RemoveField(
            model_name='facultytimetable',
            name='period2',
        ),
        migrations.AddField(
            model_name='facultytimetable',
            name='period2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period2', to='StudentManagement.Period'),
        ),
        migrations.RemoveField(
            model_name='facultytimetable',
            name='period3',
        ),
        migrations.AddField(
            model_name='facultytimetable',
            name='period3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period3', to='StudentManagement.Period'),
        ),
        migrations.RemoveField(
            model_name='facultytimetable',
            name='period4',
        ),
        migrations.AddField(
            model_name='facultytimetable',
            name='period4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period4', to='StudentManagement.Period'),
        ),
        migrations.RemoveField(
            model_name='facultytimetable',
            name='period5',
        ),
        migrations.AddField(
            model_name='facultytimetable',
            name='period5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period5', to='StudentManagement.Period'),
        ),
    ]
