# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0009_auto_20160731_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='section',
        ),
        migrations.AddField(
            model_name='period',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentManagement.Class'),
        ),
    ]
