# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0011_auto_20160731_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentManagement.Class'),
        ),
        migrations.AlterField(
            model_name='period',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentManagement.Subject'),
        ),
    ]
