# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0012_auto_20160801_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultytimetable',
            name='period1',
        ),
        migrations.RemoveField(
            model_name='facultytimetable',
            name='period2',
        ),
        migrations.RemoveField(
            model_name='facultytimetable',
            name='period3',
        ),
        migrations.RemoveField(
            model_name='facultytimetable',
            name='period4',
        ),
        migrations.RemoveField(
            model_name='facultytimetable',
            name='period5',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='schedule',
        ),
        migrations.AddField(
            model_name='period',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentManagement.Faculty'),
        ),
        migrations.DeleteModel(
            name='FacultyTimeTable',
        ),
    ]
